Name:           ros-melodic-photo
Version:        1.0.3
Release:        1%{?dist}
Summary:        ROS photo package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/photo
Source0:        %{name}-%{version}.tar.gz

Requires:       libgphoto2-devel
Requires:       opencv-devel
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-self-test
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
BuildRequires:  libgphoto2-devel
BuildRequires:  opencv-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-self-test
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs

%description
The photo package provides access to digital cameras. Much of the underlying
functionality is provide by the gPhoto libary. The system package
libgphoto2-2-dev or equivalent is required.&gt;

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri May 03 2019 Philip Roan <Philip.Roan@us.bosch.com> - 1.0.3-1
- Autogenerated by Bloom

* Tue Apr 30 2019 Philip Roan <Philip.Roan@us.bosch.com> - 1.0.3-0
- Autogenerated by Bloom

* Wed Mar 13 2019 Philip Roan <Philip.Roan@us.bosch.com> - 1.0.2-0
- Autogenerated by Bloom

